# Check health
GET http://localhost:40100/v1/health

### "###" used as request to request separater 

# Create post
POST http://localhost:40100/v1/posts
content-type: application/json

{
    "title": "New post",
    "content": "Hello there this is my first post",
    "tags": ["tag1"]
}

### Get post by id

GET http://localhost:40100/v1/posts/1